SELECT TOP (1000) [Sales Date]
      ,[Store Name]
      ,[Store Type]
      ,[Store Continent]
      ,[Store Country]
      ,[Store Province]
      ,[Store City]
      ,[Employee Count]
      ,[Area Size]
      ,[Product Category]
      ,[Product Subcategory]
      ,[Product]
      ,[Color]
      ,[Customer Continent]
      ,[Customer Country]
      ,[Customer Province]
      ,[Customer City]
      ,[Customer Birth Date]
      ,[Customer Type]
      ,[Customer Education]
      ,[Customer Gender]
      ,[House Owner]
      ,[Martial Status]
      ,[Number of Cars]
      ,[Number of Children]
      ,[Customer Occupation]
      ,[Customer Income]
      ,[Order Number]
      ,[Order Line]
      ,[Unit Cost]
      ,[Unit Price]
      ,[Sales Quantity]
      ,[Return Quantity]
      ,[Return Amount]
      ,[Discount Quantity]
      ,[Discount Amount]
      ,[Total Cost]
      ,[Sales Amount]
  FROM [dbo].[vStoreRegionProductCustomerOnlineSales_2008_Q1]

  SELECT TOP(10) [Sales Date]
  FROM [dbo].[vStoreRegionProductCustomerOnlineSales_2008_Q1]